# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/DevSam/바탕화면/gui1.0.0.ui'
#
# Created: Tue May  6 23:08:59 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 782, 498))
        self.page_3.setObjectName("page_3")
        self.btn_fstart = QtGui.QPushButton(self.page_3)
        self.btn_fstart.setGeometry(QtCore.QRect(0, 0, 85, 27))
        self.btn_fstart.setObjectName("btn_fstart")
        self.btn_fshutdown = QtGui.QPushButton(self.page_3)
        self.btn_fshutdown.setGeometry(QtCore.QRect(0, 30, 85, 27))
        self.btn_fshutdown.setObjectName("btn_fshutdown")
        self.btn_fstatus = QtGui.QPushButton(self.page_3)
        self.btn_fstatus.setGeometry(QtCore.QRect(0, 60, 85, 27))
        self.btn_fstatus.setObjectName("btn_fstatus")
        self.groupBox = QtGui.QGroupBox(self.page_3)
        self.groupBox.setGeometry(QtCore.QRect(0, 100, 771, 381))
        self.groupBox.setObjectName("groupBox")
        self.btn_fadd = QtGui.QPushButton(self.groupBox)
        self.btn_fadd.setGeometry(QtCore.QRect(520, 20, 85, 27))
        self.btn_fadd.setObjectName("btn_fadd")
        self.txt_portnum = QtGui.QLineEdit(self.groupBox)
        self.txt_portnum.setGeometry(QtCore.QRect(100, 20, 171, 27))
        self.txt_portnum.setObjectName("txt_portnum")
        self.cb_protocol = QtGui.QComboBox(self.groupBox)
        self.cb_protocol.setGeometry(QtCore.QRect(280, 20, 51, 27))
        self.cb_protocol.setObjectName("cb_protocol")
        self.cb_protocol.addItem("")
        self.cb_protocol.addItem("")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.label.setObjectName("label")
        self.txtAll = QtGui.QTextEdit(self.groupBox)
        self.txtAll.setGeometry(QtCore.QRect(0, 50, 781, 331))
        self.txtAll.setObjectName("txtAll")
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(430, 20, 81, 27))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.cb_inout = QtGui.QComboBox(self.groupBox)
        self.cb_inout.setGeometry(QtCore.QRect(340, 20, 81, 27))
        self.cb_inout.setObjectName("cb_inout")
        self.cb_inout.addItem("")
        self.cb_inout.addItem("")
        self.cb_inout.addItem("")
        self.txt_log = QtGui.QTextEdit(self.page_3)
        self.txt_log.setGeometry(QtCore.QRect(90, 0, 691, 84))
        self.txt_log.setObjectName("txt_log")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 782, 498))
        self.page_4.setObjectName("page_4")
        self.toolBox.addItem(self.page_4, "")
        self.horizontalLayout.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.btn_fshutdown, QtCore.SIGNAL("clicked()"), MainWindow.btnShutdown)
        QtCore.QObject.connect(self.btn_fstatus, QtCore.SIGNAL("clicked()"), MainWindow.btnStatus)
        QtCore.QObject.connect(self.btn_fstart, QtCore.SIGNAL("clicked()"), MainWindow.btnStart)
        QtCore.QObject.connect(self.btn_fadd, QtCore.SIGNAL("clicked()"), MainWindow.btnAdd)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fstart.setText(QtGui.QApplication.translate("MainWindow", "방화벽 실행", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fshutdown.setText(QtGui.QApplication.translate("MainWindow", "방화벽 종료", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fstatus.setText(QtGui.QApplication.translate("MainWindow", "상태 확인", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "방화벽 정책", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fadd.setText(QtGui.QApplication.translate("MainWindow", "정책 추가", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_protocol.setItemText(0, QtGui.QApplication.translate("MainWindow", "tcp", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_protocol.setItemText(1, QtGui.QApplication.translate("MainWindow", "udp", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Port number :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "ACCEPT", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "REJECT", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_inout.setItemText(0, QtGui.QApplication.translate("MainWindow", "BOTH", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_inout.setItemText(1, QtGui.QApplication.translate("MainWindow", "INPUT", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_inout.setItemText(2, QtGui.QApplication.translate("MainWindow", "OUTPUT", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("MainWindow", "방화벽", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), QtGui.QApplication.translate("MainWindow", "Page 2", None, QtGui.QApplication.UnicodeUTF8))

